import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import * as PDFLib from 'pdf-lib';
import {createCanvas,DOMMatrix,Path2D,ImageData,GlobalFonts} from '@napi-rs/canvas';
import Tesseract from 'tesseract.js';
import nspell from 'nspell';
import jsQR from 'jsqr';
const root=fileURLToPath(new URL('../',import.meta.url));
process.chdir(root+'dist');
Object.assign(globalThis,{PDFLib,DOMMatrix,Path2D,ImageData,jsQR,SpellTools:{createDictionary:(a,d)=>nspell(a,d)},document:{createElement:()=>createCanvas(1,1)}});
const realFetch=globalThis.fetch;
globalThis.fetch=async(url,opts)=>String(url).startsWith('file:')?new Response(await readFile(new URL(url))):realFetch(url,opts);
globalThis.Tesseract={createWorker:async()=>{const w=await Tesseract.createWorker('eng',1,{langPath:root+'dist/vendor/ocr',cacheMethod:'none',gzip:true});return {recognize:(c,...rest)=>w.recognize(c.toBuffer('image/png'),...rest),terminate:()=>w.terminate()};}};
const {analyzePdf,pdfjs}=await import('../dist/analyzer.js');
pdfjs.GlobalWorkerOptions.workerSrc=root+'dist/vendor/pdf.worker.mjs';
GlobalFonts.registerFromPath(root+'node_modules/pdfjs-dist/standard_fonts/LiberationSans-Regular.ttf','FixtureFont');
test('a raster-only PDF gets real OCR, spelling, date and reference checks',async()=>{
 const c=createCanvas(1200,800),ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='black';ctx.font='52px FixtureFont';
 for(const [text,y] of [['Welcomme to the ceremony',130],['Aarav Sharmma',260],['Friday, 26 September 2026',390],['The Garden Room',520]])ctx.fillText(text,70,y);
 const doc=await PDFLib.PDFDocument.create();const p=doc.addPage([600,400]),img=await doc.embedPng(c.toBuffer('image/png'));p.drawImage(img,{x:0,y:0,width:600,height:400});const bytes=await doc.save();
 await mkdir(root+'tests/fixtures',{recursive:true});await writeFile(root+'tests/fixtures/scanned-invitation.pdf',bytes);
 const result=await analyzePdf(bytes,{type:'invitation',dpi:150,margin:3,bleed:false,ocr:true,spelling:true,colourTarget:'cmyk',references:{names:['Aarav Sharma'],venue:'The Garden Room',date:'2026-09-26'}},()=>{},new AbortController().signal);
 assert.equal(result.pages[0].text,'');assert.match(result.pages[0].ocrText,/Welcomme/i);
 assert.ok(result.findings.some(f=>f.category==='spelling'&&f.title.includes('Welcomme')));
 assert.ok(result.findings.some(f=>f.category==='reference'&&f.title==='Name not found exactly'));
 assert.ok(result.findings.some(f=>f.category==='reference'&&f.title==='Venue appears in OCR — confirm it'));
 assert.ok(result.findings.some(f=>f.category==='dates'&&f.title==='Possible date issue in OCR text'));
 assert.ok(result.findings.some(f=>f.category==='colour'&&f.severity==='warning'));
 assert.ok(!result.findings.some(f=>f.category==='fonts'&&f.severity==='warning'));
 assert.ok(!result.findings.some(f=>f.category==='reference'&&f.severity==='pass'));
});
