import {PDFDocument,StandardFonts,rgb} from 'pdf-lib';
import QRCode from 'qrcode';
import {mkdir,writeFile} from 'node:fs/promises';
const pdf=await PDFDocument.create();
const regular=await pdf.embedFont(StandardFonts.Helvetica);
const serif=await pdf.embedFont(StandardFonts.TimesRoman);
const italic=await pdf.embedFont(StandardFonts.TimesRomanItalic);
const page=pdf.addPage([360,504]);
const blue=rgb(.18,.29,.65),ink=rgb(.12,.17,.25);
page.drawRectangle({x:0,y:0,width:360,height:504,color:rgb(.96,.97,1)});
page.drawRectangle({x:20,y:23,width:320,height:458,borderWidth:.6,borderColor:blue});
const center=(s,y,size,font=regular,color=ink)=>page.drawText(s,{x:(360-font.widthOfTextAtSize(s,size))/2,y,size,font,color});
center('A SAMPLE INVITATION',451,9,regular,blue);
center('The little',377,37,serif);
center('things matter.',335,37,italic,blue);
center('AN EVENING OF GOOD COMPANY',291,9);
center('Friday, 26 September 2026',254,13);
center('6:00 PM  /  The Garden Room',232,11);
const qr=await pdf.embedPng(await QRCode.toBuffer('https://example.com',{width:192,margin:4,errorCorrectionLevel:'M'}));
page.drawImage(qr,{x:130,y:91,width:100,height:100});
center('Scan for the sample destination',70,8);
center('SAMPLE ONLY - NOT A REAL EVENT',42,8,regular,blue);
center('This line is deliberately too close to the cutting edge.',2,8);
pdf.setTitle('Before You Print - sample with deliberate mistakes');
pdf.setAuthor('Before You Print');
await mkdir('dist/samples',{recursive:true});
await writeFile('dist/samples/invitation-with-mistakes.pdf',await pdf.save());
console.log('Sample PDF generated. Intentional issues: weekday, image resolution, margin and bleed.');
